/* Browser adapter: sharing, imports, popovers and persistence-aware collaboration. */
(function () {
  'use strict';
  const C=MapstoneCore;
  const DEFAULT_ENDPOINT='https://mffysunppwqscbljooda.supabase.co/functions/v1/mapstone-api';
  const $=(sel,root=document)=>root.querySelector(sel);
  let modal=null, tip=null, activeApp=null;
  function el(tag,text,attrs={}) { const e=document.createElement(tag); if(text!==null)e.textContent=text;Object.assign(e,attrs);return e; }
  function button(text,fn){const e=el('button',text,{type:'button',className:'ms-button'});e.addEventListener('click',fn);return e;}
  function field(parent,label,type='text',value=''){const l=el('label',null,{className:'ms-field'});l.append(el('span',label));const i=el(type==='textarea'?'textarea':'input',null,{value});if(type!=='textarea')i.type=type;l.append(i);parent.append(l);return i;}
  function download(data,name){const blob=new Blob([typeof data==='string'?data:JSON.stringify(data,null,2)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob);const a=el('a',null,{href:url,download:name});a.click();setTimeout(()=>URL.revokeObjectURL(url),4000);}
  function status(app,message){if(app._syncLabel)app._syncLabel.textContent=message;}
  function fitWidth(app){if(!app._board)return;const weeks=Array.from({length:app.state.cfg.months},(_,i)=>app.weeksIn(i)).reduce((a,b)=>a+b,0);const value=Math.max(app.ZMIN||4,Math.min(app.ZMAX||640,(app._board.clientWidth-218)/weeks));app.mutate(d=>{d.cfg.weekPx=value;},false);app._board.scrollLeft=0;}
  function toggleFocus(app){hideTip();const focus=!app.state.focusMode;app.setState({focusMode:focus,sel:null,editing:null});requestAnimationFrame(()=>fitWidth(app));if(focus){const notice=el('div','전체보기 · Esc 또는 F 키로 돌아오기',{className:'ms-focus-hint'});app.root.append(notice);setTimeout(()=>notice.remove(),2500);}}
  function hideTip(){tip?.remove();tip=null;}
  function showTip(app,event){hideTip();if(app.drag)return;const it=app.state.items.find(i=>i.id===event.currentTarget.dataset.id);if(!it)return;const text=it.kind==='sticky'?it.label:it.memo;if(!text||app.state.editing===it.id)return;tip=el('div',text,{className:'ms-tooltip'});tip.setAttribute('role','tooltip');document.body.append(tip);const r=event.currentTarget.getBoundingClientRect();const b=tip.getBoundingClientRect();tip.style.left=Math.max(8,Math.min(r.left,innerWidth-b.width-8))+'px';const below=r.bottom+8;tip.style.top=Math.max(8,below+b.height>innerHeight-8?r.top-b.height-8:below)+'px';}
  function closeModal(){if(!modal)return;const old=modal;modal=null;old.close();old.remove();}
  function createModal(title){closeModal();hideTip();const d=el('dialog',null,{className:'ms-dialog'});const head=el('header');head.append(el('h2',title),button('닫기',closeModal));d.append(head);const body=el('div',null,{className:'ms-dialog-body'});d.append(body);d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}});d.addEventListener('close',()=>{if(modal===d)modal=null;d.remove();});document.body.append(d);modal=d;d.showModal();return body;}
  async function request(endpoint,path,credential,method='GET',body,auth='code'){
    const names={admin:'X-Mapstone-Admin',share:'X-Mapstone-Password',code:'X-Mapstone-Code'};
    const headers={'Content-Type':'application/json',[auth===true?names.admin:(names[auth]||names.code)]:credential};
    const res=await fetch(endpoint+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(20000),cache:'no-store'});
    if(res.status===304)return null;
    const data=await res.json().catch(()=>({error:'서버 응답을 읽을 수 없습니다.'}));
    if(!res.ok){const e=new Error(data.error||'연결 실패 ('+res.status+')');e.status=res.status;e.data=data;throw e;}return data;
  }
  class Sync {
    constructor(app){this.app=app;this.endpoint=DEFAULT_ENDPOINT;this.code='';this.path='/room';this.auth='code';this.readOnly=false;this.base=null;this.revision=0;this.busy=false;this.conflict=null;this.timer=setInterval(()=>this.tick(),2000);this.alive=true;}
    schedule(){if(this.base && !C.equal(this.base,this.app.dataDocument()))status(this.app,'공동 편집 · 변경 사항 전송 대기');}
    async join(code){this.path='/room';this.auth='code';this.readOnly=false;if(this.busy)throw new Error('저장 완료 후 다시 시도하세요.');if(!/^[A-Za-z0-9_-]{24,128}$/.test(code))throw new Error('발급된 접속 코드를 입력하세요.');const remote=await request(this.endpoint,this.path,code);if(!this.alive)return;this.app.flushSave();this.code=code;this.id=remote.id;this.revision=remote.revision;this.base=C.validate(remote.document);this.conflict=null;this.app.KEY='mapstone.room.'+remote.id;let value=this.base;
      try{const raw=localStorage.getItem(this.app.KEY),base=localStorage.getItem(this.app.KEY+'.base');if(raw && base){const local=C.validate(JSON.parse(raw)),oldBase=C.validate(JSON.parse(base));const merged=C.merge(oldBase,local,this.base);value=merged.document;if(merged.conflicts.length){this.conflict={remote,paths:merged.conflicts};value=local;}}}catch(e){status(this.app,'로컬 복구본 확인 필요: '+e.message);}
      this.app._savedData=null;this.app._queuedData=null;clearTimeout(this.app._t);this.app.setState({...value,sel:null,editing:null,hist:[],future:[]});this.persistBase();sessionStorage.setItem('mapstone.connection',code);status(this.app,this.conflict?'충돌 발견 · 접속 코드 메뉴에서 해결':'공동 편집 연결 · r'+this.revision);this.tick();}
    async joinShare(id,password){if(!/^[0-9a-f-]{36}$/i.test(id))throw new Error('공유 링크가 올바르지 않습니다.');const remote=await request(this.endpoint,'/share/'+id,password,'GET',undefined,'share');this.app.flushSave();this.path='/share/'+id;this.auth='share';this.readOnly=remote.permission==='view';this.code=password;this.id=id;this.revision=remote.revision;this.base=C.validate(remote.document);this.conflict=null;this.app.KEY='mapstone.share.'+id;this.app._savedData=null;this.app._queuedData=null;clearTimeout(this.app._t);this.app.setState({...this.base,sel:null,editing:null,hist:[],future:[]});this.persistBase();sessionStorage.setItem('mapstone.share',JSON.stringify({id,password}));status(this.app,(this.readOnly?'보기 전용 공유':'공동 편집 공유')+' · r'+this.revision);}
    persistBase(){try{localStorage.setItem(this.app.KEY+'.base',JSON.stringify(this.base));}catch(e){status(this.app,'복구 정보 저장 실패 · JSON 백업 필요');}}
    async tick(){if(!this.alive||this.busy||!this.code||!this.base||this.conflict||Date.now()<(this.retryAt||0))return;const app=this.app;if(app.drag||app.state.editing||modal||['INPUT','TEXTAREA'].includes(document.activeElement?.tagName))return;this.busy=true;const current=app.dataDocument(),base=C.clone(this.base);try{
        const changed=!C.equal(current,base);if(this.readOnly&&changed){app.setState({...base,sel:null,editing:null,hist:[],future:[]});status(app,'보기 전용 공유 · 변경할 수 없습니다.');return;}const remote=changed?await request(this.endpoint,this.path,this.code,'PUT',{revision:this.revision,document:C.validate(current)},this.auth):await request(this.endpoint,this.path+'?after='+this.revision,this.code,'GET',undefined,this.auth);
        if(!this.alive||!remote)return;
        const latest=app.dataDocument(),merged=C.merge(changed?current:base,latest,C.validate(remote.document));
        if(merged.conflicts.length){this.conflict={remote,paths:merged.conflicts};status(app,'편집 충돌 · 접속 코드 메뉴에서 해결');return;}
        this.base=C.validate(remote.document);this.revision=remote.revision;this.persistBase();if(!C.equal(latest,merged.document))app.setState({...merged.document,sel:null,editing:null,hist:[],future:[]});status(app,'공동 저장 완료 · r'+this.revision);
      }catch(e){if(!this.alive)return;if(e.status===409&&e.data.room){const remote=e.data.room,merged=C.merge(base,app.dataDocument(),remote.document);if(merged.conflicts.length){this.conflict={remote,paths:merged.conflicts};status(app,'편집 충돌 · 접속 코드 메뉴에서 해결');}else{this.base=C.validate(remote.document);this.revision=remote.revision;this.persistBase();app.setState({...merged.document,hist:[],future:[]});status(app,'다른 사용자 수정 자동 병합 · 전송 대기');}}else{status(app,'공동 저장 실패 · '+e.message);this.retryAt=Date.now()+10000;}}
      finally{this.busy=false;}}
    resolve(useLocal){const c=this.conflict;if(!c)return;if(!useLocal){download(this.app.dataDocument(),'mapstone-conflict-local-backup.json');this.app.setState({...C.validate(c.remote.document),sel:null,editing:null,hist:[],future:[]});}this.base=C.validate(c.remote.document);this.revision=c.remote.revision;this.conflict=null;this.persistBase();status(this.app,'충돌 해결 · 동기화 대기');}
    leave(){if(this.busy)throw new Error('저장 진행 중입니다. 잠시 후 다시 시도하세요.');if(this.base&&!C.equal(this.base,this.app.dataDocument())&&!window.confirm('서버에 보내지 못한 변경이 있습니다. 로컬 복구본을 남기고 연결을 종료할까요?'))return;this.app.flushSave();this.code='';this.base=null;this.conflict=null;this.path='/room';this.auth='code';this.readOnly=false;sessionStorage.removeItem('mapstone.connection');sessionStorage.removeItem('mapstone.share');this.app.KEY='mapstone.timeline.v1';this.app._savedData=null;status(this.app,'로컬 모드 · 공유 연결 종료');}
    dispose(){this.alive=false;clearInterval(this.timer);}
  }
  const example={schemaVersion:1,title:'2개월 프로젝트',cfg:{startY:2026,startM:9,months:2,weekPx:100,weekMode:'actual',laneH:44,magnet:true,overlap:'moveOther'},rows:[{id:'product',name:'기획 · 개발'}],items:[{id:'design',kind:'chev',row:'product',lane:0,s:0,e:0.5,label:'요구사항 분석',color:'#5b3fd1',span:1,variant:'solid',memo:'PRD 요구사항 검토',hideDuration:false},{id:'build',kind:'chev',row:'product',lane:0,s:0.5,e:1.75,label:'구현 및 검증',color:'#0078d4',span:1,variant:'solid',memo:''}],notes:[],now:0,versions:[]};
  function imports(app,body){
    body.append(el('p','PRD를 LLM에 제공하고 “아래 일정 데이터 형식으로 JavaScript의 const schedule = {...};를 산출해 줘”라고 요청하세요. 결과를 붙여넣거나 .js / .json 파일로 가져오면 일정에 반영됩니다. 함수 실행, 외부 호출, 계산식은 지원하지 않으며 객체·배열·문자·숫자·true/false만 사용하세요.'));
    const help=el('details');help.append(el('summary','LLM 요청문 · 데이터 예제'));const prompt='PRD를 분석해 아래 형식의 const schedule 데이터만 작성해 줘. 시작 월을 0으로 하고 s/e는 개월 단위(5개월 미만은 0.125 단위)로 지정해. rows의 id와 items의 row를 일치시키고 블록 id는 고유하게 지정해. 실행 함수나 계산식 없이 데이터 리터럴로 출력해.\n\nconst schedule = '+JSON.stringify(example,null,2)+';';help.append(el('pre',prompt));help.append(button('요청문 복사',async()=>{try{await navigator.clipboard.writeText(prompt);}catch{download(prompt,'mapstone-llm-prompt.txt');}}));body.append(help);
    const input=field(body,'JavaScript / JSON 일정 데이터','textarea');input.rows=10;input.placeholder='const schedule = { title: "프로젝트", cfg: {...}, rows: [...], items: [...] };';
    const file=field(body,'데이터 파일 선택','file');file.accept='.js,.json,text/javascript,application/json';file.addEventListener('change',async()=>{if(file.files[0]){if(file.files[0].size>8*1024*1024){message.textContent='파일은 8MB 이하여야 합니다.';return;}input.value=await file.files[0].text();}});
    const message=el('p','',{className:'ms-message'});message.setAttribute('role','status');const preview=el('div');let parsed=null;
    const apply=button('검토한 일정으로 교체',()=>{try{if(!parsed)return;const fresh=C.parseImport(input.value);if(!C.equal(fresh,parsed)){message.textContent='입력이 바뀌었습니다. 다시 검토하세요.';apply.disabled=true;return;}download(app.dataDocument(),'mapstone-before-import.json');app.importDocument(parsed);closeModal();requestAnimationFrame(()=>fitWidth(app));}catch(e){message.textContent=e.message;}});apply.disabled=true;
    input.addEventListener('input',()=>{parsed=null;apply.disabled=true;});
    body.append(button('데이터 검토',()=>{try{parsed=C.parseImport(input.value);preview.replaceChildren(el('strong',parsed.title),el('p',parsed.cfg.months+'개월 · '+parsed.rows.length+'개 구분 · '+parsed.items.length+'개 블록'));preview.append(el('p',parsed.items.slice(0,12).map(i=>i.label).join(' / ')));message.textContent='기존 일정은 JSON으로 백업한 후 교체합니다. 실행 취소도 가능합니다.';apply.disabled=false;}catch(e){parsed=null;apply.disabled=true;message.textContent=e.message;}}),preview,apply,message);
    body.append(el('hr'),el('h3','이미지 가져오기'),el('p','일정표 이미지를 편집 가능한 블록으로 분석하거나, 기존 방식대로 일정 위에 참조 이미지로 배치할 수 있습니다.'));
    const image=field(body,'이미지 파일 (최대 2MB)','file');image.accept='image/png,image/jpeg,image/webp';
    const readImage=async()=>{const f=image.files[0];if(!f)throw new Error('이미지를 먼저 선택하세요.');if(f.size>2*1024*1024||!['image/png','image/jpeg','image/webp'].includes(f.type))throw new Error('2MB 이하 PNG/JPEG/WebP를 선택하세요.');const src=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(f);});return {f,src};};
    const analyze=button('편집 가능한 일정으로 분석',async()=>{try{if(!app.sync.code)throw new Error('이미지 분석은 공동 편집 접속 코드로 연결한 뒤 사용할 수 있습니다.');analyze.disabled=true;message.textContent='이미지에서 일정 구조와 날짜를 분석하고 있습니다…';const {src}=await readImage();const result=await request(app.sync.endpoint,'/analyze-image',app.sync.code,'POST',{image:src});const document=C.validate(result.document);message.textContent='분석이 완료되었습니다.';download(app.dataDocument(),'mapstone-before-image-analysis.json');app.importDocument(document);closeModal();requestAnimationFrame(()=>fitWidth(app));}catch(e){message.textContent=e.message;}finally{analyze.disabled=false;}});
    const overlay=button('참조 이미지로 추가',async()=>{try{const {f,src}=await readImage();const img=new Image();img.src=src;await img.decode();const w=Math.min(600,img.width),h=w*img.height/img.width;const id=C.uid();app.mutate(d=>{d.items.push({id,kind:'image',src,label:f.name,row:'',lane:0,span:1,s:0,e:0,y:70,w,h,color:'#ffffff',variant:'solid',memo:''});});app.setState({sel:id});closeModal();}catch(e){message.textContent=e.message;}});
    body.append(analyze,overlay,el('p','분석 기능은 표의 행 이름, 작업명, 시작·종료 시점을 읽어 블록으로 만듭니다. 흐릿하거나 날짜가 생략된 이미지는 검토 후 조정하세요.'));
  }
  function workspace(app,body){const sync=app.sync,shareId=new URLSearchParams(location.search).get('share'),message=el('p','',{className:'ms-message'});message.setAttribute('role','status');
    if(shareId){body.append(el('p','공유받은 일정입니다. 공유자가 설정한 접속 암호를 입력하세요.'));const password=field(body,'접속 암호','password');password.autocomplete='current-password';body.append(button('공유 일정 열기',async()=>{try{message.textContent='접속 중…';await sync.joinShare(shareId,password.value);closeModal();}catch(e){message.textContent=e.message;}}),message);return;}
    body.append(el('p','현재 일정을 링크로 공유합니다. 링크에는 암호가 포함되지 않으며, 받은 사람은 설정한 접속 암호를 입력해야 합니다.'));
    const sharePassword=field(body,'접속 암호 (6자 이상)','password');sharePassword.autocomplete='new-password';
    const permissionLabel=el('label',null,{className:'ms-field'});permissionLabel.append(el('span','공유 권한'));const permission=el('select');permission.append(el('option','보기만 가능',{value:'view'}),el('option','함께 편집',{value:'edit'}));permission.value='view';permissionLabel.append(permission);body.append(permissionLabel);
    const shareResult=el('div');
    body.append(button('공유 링크 만들기',async()=>{try{message.textContent='공유 링크 생성 중…';const result=await request(sync.endpoint,'/share','','POST',{password:sharePassword.value,permission:permission.value,document:C.validate(app.dataDocument())});const link=location.origin+location.pathname+'?share='+encodeURIComponent(result.id);sessionStorage.setItem('mapstone.owner.'+result.id,result.code);shareResult.replaceChildren(el('strong',permission.value==='edit'?'함께 편집 링크':'보기 전용 링크'),el('code',link),button('링크 복사',()=>navigator.clipboard.writeText(link).catch(()=>{})));message.textContent='링크를 만든 뒤 접속 암호는 별도로 전달하세요.';}catch(e){message.textContent=e.message;}}),shareResult,message);
    const legacy=el('details');legacy.append(el('summary','기존 접속 코드 · DB 관리'));const legacyBody=el('div');legacy.append(legacyBody);body.append(legacy);body=legacyBody;
    body.append(el('p','기존 편집 코드로 공동 편집하거나 관리자 기능을 사용합니다.'));
    const code=field(body,'편집용 접속 코드','password',sync.code);code.autocomplete='off';
    body.append(button('접속',async()=>{try{message.textContent='접속 중…';await sync.join(code.value.trim());message.textContent='연결했습니다.';closeModal();}catch(e){message.textContent=e.message;}}),button('연결 종료',()=>{try{sync.leave();if(!sync.code)closeModal();}catch(e){message.textContent=e.message;}}),button('코드 표시 / 숨김',()=>{code.type=code.type==='password'?'text':'password';}),message);
    if(sync.conflict){const box=el('section',null,{className:'ms-conflict'});box.append(el('h3','같은 데이터가 동시에 수정되었습니다'),el('p',sync.conflict.paths.join(', ')),button('내 변경을 우선 반영',()=>{sync.resolve(true);closeModal();}),button('서버 내용을 사용 (내 변경 백업)',()=>{sync.resolve(false);closeModal();}));body.append(box);}
    const admin=el('details');admin.append(el('summary','DB 관리 · 관리자 전용'));const area=el('div');admin.append(area);body.append(admin);area.append(el('p','관리자 키로 일정 생성·목록·변경 이력·복원·접속 코드 재발급·보관을 관리합니다. 관리자 키는 브라우저에 저장하지 않습니다.'));
    const key=field(area,'관리자 키','password');key.autocomplete='off';const name=field(area,'새 일정 이름','text',app.state.title);const list=el('div',null,{className:'ms-room-list'});
    const run=async fn=>{try{message.textContent='처리 중…';await fn();message.textContent='완료';}catch(e){message.textContent=e.message;}};
    const reveal=(result)=>{const b=el('div',null,{className:'ms-secret'});b.append(el('strong','발급된 편집 코드 (복사해 참여자에게 전달)'),el('code',result.code));b.append(button('코드 복사',()=>navigator.clipboard.writeText(result.code).catch(()=>{})));list.prepend(b);};
    async function load(){const rooms=await request(sync.endpoint,'/rooms',key.value,'GET',undefined,true);list.replaceChildren();for(const r of rooms){const row=el('section');row.append(el('strong',r.title),el('p','r'+r.revision+' · '+new Date(r.updated_at).toLocaleString()+(r.archived?' · 보관됨':'')));row.append(button('접속 코드 재발급',()=>run(async()=>{if(!confirm('기존 접속 코드는 즉시 사용할 수 없게 됩니다. 재발급할까요?'))return;reveal(await request(sync.endpoint,'/rooms/'+r.id+'/rotate',key.value,'POST',{},true));})),button(r.archived?'보관 해제':'보관',()=>run(async()=>{if(!confirm('이 일정의 보관 상태를 변경할까요?'))return;await request(sync.endpoint,'/rooms/'+r.id,key.value,'PATCH',{archived:!r.archived},true);await load();})),button('변경 이력',()=>run(async()=>{const history=await request(sync.endpoint,'/rooms/'+r.id+'/history',key.value,'GET',undefined,true);const historyBox=el('div');row.append(historyBox);for(const h of history){historyBox.append(button('r'+h.revision+' · '+new Date(h.created_at).toLocaleString()+' 복원',()=>run(async()=>{if(!confirm('선택 버전으로 복원할까요? 현재 상태도 서버 이력에 보관됩니다.'))return;await request(sync.endpoint,'/rooms/'+r.id+'/restore',key.value,'POST',{revision:h.revision,expectedRevision:r.revision},true);await load();})));}})));list.append(row);}}
    area.append(button('일정 목록 불러오기',()=>run(load)),button('현재 일정으로 새 공유방 생성',()=>run(async()=>{const document=app.dataDocument();document.title=name.value||document.title;const result=await request(sync.endpoint,'/rooms',key.value,'POST',{document:C.validate(document)},true);await load();reveal(result);})),list);
    body.append(el('details'));const api=body.lastChild;api.append(el('summary','외부 앱 · LLM 연동'),el('p','JSON 데이터 계약과 REST API를 제공합니다. GET /room으로 문서·revision을 읽고 PUT /room에 revision과 수정 문서를 전달합니다. 인증 헤더는 X-Mapstone-Code입니다. 409 응답은 최신 문서를 다시 읽고 병합해야 함을 뜻합니다.'),el('code',DEFAULT_ENDPOINT),button('현재 일정 JavaScript 다운로드',()=>download('const schedule = '+JSON.stringify(app.dataDocument(),null,2)+';','mapstone-schedule.js')));
  }
  function open(app,page){const body=createModal(page==='import'?'일정 · 이미지 가져오기':'공유');if(page==='import')imports(app,body);else workspace(app,body);}
  function attach(app){activeApp=app;app._msAlive=true;app.sync=new Sync(app);
    if(!$('#mapstone-ui-style')){const style=el('style',null,{id:'mapstone-ui-style'});style.textContent='.ms-dialog{position:fixed;border:1px solid #dce0e5;border-radius:14px;padding:0;width:min(780px,94vw);max-height:90dvh;color:#181a1b;background:white;font:14px/1.6 system-ui;z-index:10000}.ms-dialog::backdrop{background:rgba(10,18,30,.48)}.ms-dialog header{display:flex;align-items:center;justify-content:space-between;position:sticky;top:0;background:#fff;padding:16px 22px;border-bottom:1px solid #e7ebee;z-index:2}.ms-dialog h2{margin:0;font-size:20px}.ms-dialog-body{padding:20px 22px}.ms-dialog .ms-button{margin:4px 6px 4px 0}.ms-field{display:flex;flex-direction:column;gap:5px;margin:14px 0}.ms-field input,.ms-field textarea{padding:10px;border:1px solid #bac4cf;border-radius:6px;font:inherit;width:100%;box-sizing:border-box}.ms-field textarea{font:12px/1.5 ui-monospace,monospace}.ms-dialog details{border:1px solid #e0e5eb;border-radius:8px;padding:12px;margin:16px 0}.ms-dialog summary{cursor:pointer;font-weight:650}.ms-dialog pre{white-space:pre-wrap;max-height:300px;overflow:auto;font-size:12px}.ms-dialog code{overflow-wrap:anywhere;user-select:text}.ms-dialog .ms-message{color:#8a0050;white-space:pre-line}.ms-room-list section{border-top:1px solid #e0e5eb;padding:14px 0}.ms-secret,.ms-conflict{padding:12px;background:#fff5d9;border-radius:6px}.ms-secret code{display:block;margin:8px 0}.ms-tooltip{position:fixed;z-index:1500;pointer-events:none;max-width:min(360px,calc(100vw - 16px));max-height:60vh;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere;padding:12px 14px;border:1px solid #c5cfda;background:#fff;color:#181a1b;box-shadow:0 6px 24px #0003;border-radius:8px;font:13px/1.6 system-ui}.ms-focus-hint{position:fixed;bottom:18px;left:50%;transform:translateX(-50%);z-index:550;background:#181a1bdd;color:white;border-radius:20px;padding:8px 18px;font:13px system-ui}.ms-sync-label{font:11px system-ui;color:#655270;max-width:250px}.ms-button:disabled{opacity:.4;cursor:default}@media print{.ms-dialog,.ms-tooltip,.ms-focus-hint{display:none!important}}';document.head.append(style);}
    const label=el('span','로컬 모드',{className:'ms-sync-label'});label.setAttribute('aria-live','polite');app._syncLabel=label;const toolbar=$('[data-toolbar] > div',app.root);toolbar?.append(label);
    const onKey=e=>{if(modal)return;if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)||e.metaKey||e.ctrlKey||e.altKey)return;if(e.key==='Escape'&&app.state.focusMode){e.preventDefault();toggleFocus(app);}else if(e.key.toLowerCase()==='f'){e.preventDefault();toggleFocus(app);}};
    const warn=e=>{if(app.sync.base&&!C.equal(app.sync.base,app.dataDocument())){e.preventDefault();e.returnValue='';}};
    document.addEventListener('keydown',onKey);window.addEventListener('beforeunload',warn);document.addEventListener('scroll',hideTip,true);
    let code=null;try{code=sessionStorage.getItem('mapstone.connection');}catch{}if(code)app.sync.join(code).catch(e=>status(app,'재접속 실패 · '+e.message));const shareId=new URLSearchParams(location.search).get('share');if(shareId&&!code)setTimeout(()=>open(app,'workspace'),100);
    // Public local automation interface, uses the same validator as imports and the server.
    window.mapstone={getDocument:()=>C.clone(app.dataDocument()),replaceDocument:data=>app.importDocument(data),exportJavaScript:()=>'const schedule = '+JSON.stringify(app.dataDocument(),null,2)+';',getConnection:()=>({connected:!!app.sync.code,roomId:app.sync.id,revision:app.sync.revision})};
    return ()=>{app._msAlive=false;app.sync.dispose();closeModal();hideTip();label.remove();document.removeEventListener('keydown',onKey);window.removeEventListener('beforeunload',warn);document.removeEventListener('scroll',hideTip,true);if(activeApp===app)activeApp=null;};
  }
  window.MapstoneUI={attach,open,download,toggleFocus,fitWidth,showTip,hideTip};
})();
