const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs'),vm=require('node:vm');const C=require('../mapstone-core.js');
const html=fs.readFileSync('src/timeline.dc.html','utf8'),logic=html.match(/<script type="text\/x-dc"[^>]*>([\s\S]*?)<\/script>/)[1];
function make(){let timers=new Map(),id=0,writes=0;const memory=new Map();const document={createElement:()=>({getContext:()=>({font:'',measureText:t=>({width:t.length*7})})}),addEventListener(){},removeEventListener(){}};const ctx={MapstoneCore:C,MapstoneUI:{attach(){return ()=>{}},hideTip(){}},DCLogic:class{props={};setState(p){const patch=typeof p==='function'?p(this.state):p;this.state={...this.state,...patch};this.componentDidUpdate?.();}},window:{localStorage:{getItem:k=>memory.get(k)||null,setItem:(k,v)=>{writes++;memory.set(k,v);}},addEventListener(){},removeEventListener(){},confirm:()=>true},document,console,Date,Math,JSON,setTimeout:fn=>{timers.set(++id,fn);return id;},clearTimeout:id=>timers.delete(id),requestAnimationFrame:fn=>fn(),cancelAnimationFrame(){}};vm.createContext(ctx);vm.runInContext(logic+'\nglobalThis.app=new Component()',ctx);return {app:ctx.app,ctx,memory,timers,writes:()=>writes,flush:()=>{const all=[...timers.values()];timers.clear();all.forEach(fn=>fn());}};}
test('Auto-save stops after real content saved; selection does not resave',()=>{const h=make();h.app.componentDidUpdate();h.flush();assert.equal(h.writes(),1);assert.equal(h.timers.size,0);h.app.setState({sel:h.app.state.items[0].id});h.flush();assert.equal(h.writes(),1);h.app.onTitle({currentTarget:{value:'changed'}});h.flush();assert.equal(h.writes(),2);});
test('Save failure shows warning and does not recurse',()=>{const h=make();h.ctx.window.localStorage.setItem=()=>{throw Error('QuotaExceeded');};h.app.componentDidUpdate();h.flush();assert.match(h.app.state.saved,/실패/);assert.equal(h.timers.size,0);});
test('Eighth-month snap is exact; fifth month returns quarter grid',()=>{const h=make();h.app.state.items=[];h.app.state.cfg.months=2;assert.equal(h.app.snapM(.127,'',null),.125);h.app.state.cfg.months=5;assert.equal(h.app.snapM(.127,'',null),.25);h.app.state.cfg.magnet=false;assert.equal(h.app.snapM(.1234,'',null),.1234);});
test('Two-month configuration and wider zoom accepted',()=>{const h=make();h.app.applyCfg('months',2,0);assert.equal(h.app.state.cfg.months,2);h.app.onWeekPx({currentTarget:{value:String(h.app.zoomToSlider(200))}});assert.ok(Math.abs(h.app.state.cfg.weekPx-200)<1,'200px/week round trip, got '+h.app.state.cfg.weekPx);h.app.onWeekPx({currentTarget:{value:'0'}});assert.equal(h.app.state.cfg.weekPx,h.app.ZMIN);h.app.onWeekPx({currentTarget:{value:'1000'}});assert.equal(h.app.state.cfg.weekPx,h.app.ZMAX);});
test('Zoom slider spreads the usable range instead of crowding the low end',()=>{const h=make();const t=h.app.zoomToSlider(19);assert.ok(t>200&&t<400,'default 19px/week should land mid-track, got '+t);const half=h.app.zoomFromSlider(500);assert.ok(half>40&&half<60,'mid-track should be a moderate zoom, got '+half);});
test('Start and end accept dates and round-trip through month offsets',()=>{const h=make();h.app.state.cfg.months=2;h.app.state.items=[h.app.state.items[0]];const id=h.app.state.items[0].id;h.app.state.sel=id;const it=()=>h.app.state.items.find(i=>i.id===id);h.app.onDateField({currentTarget:{dataset:{field:'s'},value:'2026-02-01'}});assert.equal(it().s,1);assert.equal(h.app.isoOf(1),'2026-02-01');h.app.onDateField({currentTarget:{dataset:{field:'e'},value:'2026-03-01'}});assert.equal(it().e,2);assert.equal(h.app.monthOfISO('2026-01-01'),0);assert.equal(h.app.monthOfISO('not-a-date'),null);assert.equal(h.app.monthOfISO('2026-02-30'),null);});
test('Mouse control notice opens on toggle and stays muted once dismissed',()=>{const h=make();h.app.toggleInteract();assert.equal(h.app.state.interact,true);assert.equal(h.app.state.mouseTipOpen,true);h.app.onMuteMouseTip({currentTarget:{checked:true}});assert.equal(h.memory.get('mapstone.mouseTip.muted'),'1');h.app.closeMouseTip();h.app.toggleInteract();assert.equal(h.app.state.mouseTipOpen,false);});
test('Renamed controls and new groups are translated in both locales',()=>{const h=make();assert.equal(h.app.DICT.ko.interact,'마우스 컨트롤');assert.equal(h.app.DICT.ko.tabSet,'전체 설정');assert.equal(h.app.DICT.ko.panelF,'설정 패널');assert.match(h.app.DICT.ko.dateHint,/마그네틱 스냅/);for(const lang of ['ko','ja'])for(const key of ['interact','tabSet','panelF','dateHint','dateSet','mouseTipMsg','dontShow','shareG','importG','shareBtn','jsonBak','helpT','helpTip'])assert.ok(h.app.DICT[lang][key],lang+'.'+key+' missing');});
test('Hide duration retains timing and survives undo',()=>{const h=make();h.app.state.sel=h.app.state.items[0].id;const start=h.app.state.items[0].s;h.app.onHideDuration({currentTarget:{checked:true}});let vals=h.app.renderVals();const block=vals.rowsView.flatMap(r=>r.chevs).find(i=>i.id===h.app.state.sel);assert.equal(block.dur,'');assert.equal(block.durIn,false);assert.equal(h.app.state.items[0].s,start);h.app.undo();assert.equal(h.app.state.items[0].hideDuration,undefined);});
test('Short schedules expose dates, 8 divisions and exact 0.125M label',()=>{const h=make();h.app.state.cfg.months=2;const v=h.app.renderVals();assert.equal(v.subdivisions.length,14);assert.equal(v.timeStep,.125);assert.equal(h.app.durOf(0,.125),'0.125M');assert.match(h.app.dateOf(.125),/2026\.01\.04/);});
test('Imported documents reject unknown kinds without replacing current state',()=>{const h=make(),before=h.app.snapshot();assert.throws(()=>h.app.importDocument({rows:[],items:[]}));assert.equal(h.app.snapshot(),before);});
test('All entry point application logic is generated identically',()=>{for(const name of ['share-timeline.dc.html','share/schedule-maker.html'])assert.equal(fs.readFileSync(name,'utf8'),html);});
test('Modal stacking and focus mode CSS protect content visibility',()=>{assert.ok(!/z-index:60;display:flex;align-items:center;justify-content:center;padding:24px/.test(html));assert.match(html,/data-focus="true".*data-toolbar/);assert.match(html,/data-resize/);});
