const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs'),vm=require('node:vm');const C=require('../mapstone-core.js');
const html=fs.readFileSync('src/timeline.dc.html','utf8'),logic=html.match(/<script type="text\/x-dc"[^>]*>([\s\S]*?)<\/script>/)[1];
test('Pinch zoom works with mouse mode off, keeps scroll anchor and clamps zoom',()=>{
  const h=make(),handlers={},el={scrollLeft:200,scrollWidth:2000,clientWidth:800,getBoundingClientRect:()=>({left:0}),addEventListener:(name,fn)=>handlers[name]=fn};
  h.app.setBoard(el);h.app.state.interact=false;let prevented=0;const before=h.app.state.cfg.weekPx;
  handlers.wheel({ctrlKey:false,deltaY:-10,clientX:300,preventDefault(){prevented++;}});assert.equal(h.app.state.cfg.weekPx,before);
  handlers.wheel({ctrlKey:true,deltaY:-10,clientX:300,preventDefault(){prevented++;}});assert.ok(h.app.state.cfg.weekPx>before);assert.ok(el.scrollLeft>200);assert.equal(prevented,1);
  handlers.wheel({ctrlKey:true,deltaY:-10000,clientX:300,preventDefault(){}});assert.equal(h.app.state.cfg.weekPx,h.app.ZMAX);
});
function heightFixture(){const h=make();h.app.state.rows=h.app.state.rows.slice(0,3).map(r=>({...r,h:140}));const it={...h.app.state.items.find(i=>i.kind==='chev'),row:h.app.state.rows[1].id,lane:1,span:1,s:1,e:2,label:'height test'};h.app.state.items=[it];h.app.renderVals();return {h,it};}
test('Vertical resize crosses row boundaries but clamps to all rows and preserves undo/save',()=>{
  for(const kind of ['chev','plain'])for(const mode of ['top','bottom']){const {h,it}=heightFixture();it.kind=kind;const before=h.app.snapshot(),bounds=h.app.heightBounds(it);
    h.app.drag={id:it.id,kind,mode,...bounds,x0:0,y0:0,snap:before,moved:false};
    h.app.onMove({clientX:0,clientY:mode==='top'?-10000:10000});const after=h.app.state.items.find(i=>i.id===it.id),box=h.app.trackBox(after);assert.equal(after.row,it.row);
    assert.equal(mode==='top'?box.top:box.bottom,mode==='top'?6:bounds.total-6);assert.ok(mode==='top'?box.localTop<0:box.localTop+box.height>140);assert.ok(h.app.state.rows.every(r=>r.h===140));
    const saved=C.parseFile(C.serializeFile(h.app.dataDocument())).items[0];assert.equal(saved.trackH,after.trackH);assert.equal(saved.trackY,after.trackY);
    h.app.onMove({clientX:0,clientY:0});assert.equal(h.app.trackBox(h.app.state.items[0]).height,bounds.height);
    h.app.stopDrag();h.app.undo();assert.equal(h.app.snapshot(),before);
  }
});
test('Height resize stops at occupied space without reflow, including keyboard and settings',()=>{
  const {h,it}=heightFixture();h.app.state.items.push({...it,id:'obstacle',row:h.app.state.rows[2].id,lane:0});h.app.renderVals();const peer=JSON.stringify(h.app.state.items[1]),g={id:it.id,mode:'bottom',...h.app.heightBounds(it)};
  h.app.mutate(d=>h.app.resizeHeight(d,g,10000));assert.equal(h.app.trackBox(h.app.state.items[0]).bottom,h.app.trackBox(h.app.state.items[1]).top-2);assert.equal(JSON.stringify(h.app.state.items[1]),peer);
  h.app.state.sel=it.id;h.app.onStep({currentTarget:{dataset:{field:'span',delta:'1'}}});h.app.onField({currentTarget:{dataset:{field:'span'},type:'number',value:'100'}});assert.equal(h.app.trackBox(h.app.state.items[0]).bottom,g.max);
  h.app.onHeightKey({key:'ArrowDown',preventDefault(){},stopPropagation(){},currentTarget:{dataset:{id:it.id,mode:'bottom'}}});assert.equal(h.app.trackBox(h.app.state.items[0]).bottom,g.max);
  const data=JSON.parse(h.app.snapshot());data.items[0].trackH=-1;assert.throws(()=>C.validate(data));data.items[0].trackH=50;data.items[0].trackY=Infinity;assert.throws(()=>C.validate(data));
});
test('Top resize respects a preceding row obstacle and connected memo follows custom height',()=>{
  const {h,it}=heightFixture();h.app.state.items.push({...it,id:'above',row:h.app.state.rows[0].id,lane:1},{id:'memo',kind:'flag',row:it.row,lane:0,span:1,s:1,e:1,label:'memo',color:it.color,targetId:it.id,linkOffset:.5,linkY:.5});h.app.renderVals();
  const g={id:it.id,mode:'top',...h.app.heightBounds(it)};h.app.mutate(d=>h.app.resizeHeight(d,g,-10000));const box=h.app.trackBox(h.app.state.items[0]);assert.equal(box.top,h.app.trackBox(h.app.state.items[1]).bottom+2);
  const view=h.app.renderVals(),f=view.rowsView.flatMap(r=>r.flags).find(i=>i.id==='memo');assert.equal(parseFloat(f.top)+11,box.localTop+box.height*.5);
  const saved=C.parseFile(C.serializeFile(h.app.dataDocument()));h.app.state.items=saved.items;assert.equal(h.app.trackBox(h.app.state.items[0]).top,box.top);
});
test('Date guide updates while dragging and disappears on release; marker has single date',()=>{
  const h=make(),it=h.app.state.items.find(i=>i.kind==='chev');h.app.drag={id:it.id,kind:'chev',mode:'r',x0:0,y0:0,s:it.s,e:it.e,snap:h.app.snapshot(),moved:false};
  h.app.onMove({clientX:45,clientY:0});let v=h.app.renderVals();assert.equal(v.dragGuides.length,1);assert.equal(v.dragGuides[0].date,h.app.isoOf(h.app.state.items.find(i=>i.id===it.id).e));h.app.stopDrag();assert.equal(h.app.renderVals().dragGuides.length,0);
  h.app.state.sel=h.app.state.items.find(i=>i.kind==='marker').id;v=h.app.renderVals();assert.equal(v.selRange,false);assert.equal(v.selStartLabel,'일자');assert.doesNotMatch(html,/\{\{ sel[SE]Date \}\}/);assert.match(html,/\{\{ nowISO \}\}/);assert.match(html,/\{\{ f.dateLabel \}\}/);
});
test('Memo connects to any band position and follows band geometry after save',()=>{
  const h=make(),band=h.app.state.items.find(i=>i.kind==='band'),flag=h.app.state.items.find(i=>i.kind==='flag');h.app.connectFlag(flag.id,band.id,.3,true,.6);
  const v=h.app.renderVals(),f=v.rowsView.flatMap(r=>r.flags).find(i=>i.id===flag.id);assert.equal(f.targetId,band.id);assert.equal(f.connected,true);assert.ok(v.linkOptions.some(i=>i.id===band.id));assert.match(f.dateLabel,/^\d{4}-\d{2}-\d{2}$/);
  const saved=C.parseFile(C.serializeFile(h.app.dataDocument())).items.find(i=>i.id===flag.id);assert.equal(saved.targetId,band.id);assert.equal(saved.linkY,.6);h.app.mutate(d=>{d.items.find(i=>i.id===band.id).e+=1;});assert.equal(h.app.state.items.find(i=>i.id===flag.id).s,band.s+(band.e+1-band.s)*.3);
});
test('Labels wrap before detaching and external labels have horizontal connectors',()=>{const h=make();assert.equal(h.app.labelFits('short label',60,34),true);assert.equal(h.app.labelFits('short label',60,16),false);assert.equal(h.app.labelFits('word'.repeat(40),60,34),false);assert.match(html,/left:100%;top:50%;width:8px;border-top/);assert.match(html,/right:100%;top:50%;width:8px;border-top/);});
test('Text analysis matches image UX and keeps file, paste, validation and review paths',()=>{const ui=fs.readFileSync('mapstone-ui.js','utf8');assert.match(ui,/2\. 텍스트 분석하기/);assert.match(ui,/button\('텍스트 분석'/);assert.match(ui,/aria-label','텍스트 지우기/);assert.match(ui,/clearText.hidden=!input.value/);assert.match(ui,/input.value='';syncText\(\);reset\('입력 내용을 지웠습니다\.'\);input.focus\(\)/);for(const old of ["button('텍스트 복사'","button('텍스트 삭제'","button('텍스트 붙여넣기'",'텍스트 붙여넣기 방법','내용 분석 → 일정으로 변환'])assert.ok(!ui.includes(old),old);assert.match(ui,/input.value=await f.text\(\)/);assert.match(ui,/dialog.addEventListener\('paste'/);assert.match(ui,/text.length>200000/);assert.match(ui,/C.parseImport\(text\)/);assert.match(ui,/검토내용 적용/);assert.match(ui,/download\(app.dataDocument\(\),'mapstone-before-import.json'\)/);});
test('Dot keeps any dropped position inside a task through resize, zoom, save and undo',()=>{const h=make(),t=h.app.state.items.find(i=>i.kind==='chev'),f=h.app.state.items.find(i=>i.kind==='flag');h.app.state.cfg.weekMode='actual';const view=()=>h.app.renderVals().rowsView.flatMap(r=>r.flags).find(v=>v.id===f.id);for(const x of [0,.23,1])for(const y of [0,.37,1]){h.app.connectFlag(f.id,t.id,x,true,y);const v=view();assert.ok(Math.abs(parseFloat(v.left)-(h.app.xOf(t.s)+h.app.wOf(t.s,t.e)*x))<.01);assert.ok(Math.abs(parseFloat(v.top)+11-(6+t.lane*h.app.state.cfg.laneH+((t.span||1)*h.app.state.cfg.laneH-12)*y))<.01);const saved=C.parseFile(C.serializeFile(h.app.dataDocument())).items.find(i=>i.id===f.id);assert.equal(saved.linkY,y);assert.equal(saved.linkOffset,x);}h.app.connectFlag(f.id,t.id,.23,true,.37);h.app.mutate(d=>{const target=d.items.find(i=>i.id===t.id);target.s+=1;target.e+=2;target.span=2;d.cfg.weekPx*=2;});const target=h.app.state.items.find(i=>i.id===t.id),v=view();assert.ok(Math.abs(parseFloat(v.left)-(h.app.xOf(target.s)+h.app.wOf(target.s,target.e)*.23))<.01);assert.ok(Math.abs(parseFloat(v.top)+11-(6+target.lane*h.app.state.cfg.laneH+(2*h.app.state.cfg.laneH-12)*.37))<.01);h.app.connectFlag(f.id,'');assert.equal(h.app.state.items.find(i=>i.id===f.id).linkY,undefined);h.app.undo();assert.equal(h.app.state.items.find(i=>i.id===f.id).linkY,.37);const bad=h.app.dataDocument();bad.items.find(i=>i.id===f.id).linkY=1.1;assert.throws(()=>C.validate(bad));});
test('Image analysis UI is simplified and offers an accessible preview delete icon',()=>{const ui=fs.readFileSync('mapstone-ui.js','utf8');for(const label of ['큰 화면 · 긴 일정표 캡처 방법','참조 이미지로만 추가','이미지 분석 → 일정으로 변환',"button('이미지 붙여넣기'","button('이미지 복사'"])assert.ok(!ui.includes(label),label);assert.match(ui,/검토내용 적용/);assert.match(ui,/apply.classList.add\('ms-primary'\)/);assert.match(ui,/aria-label','이미지 삭제/);assert.match(ui,/ms-image-preview\[hidden\]\{display:none\}/);assert.match(ui,/dialog.addEventListener\('paste'/);});
test('Export menu saves round-trippable files first and import opens the file loader',()=>{const h=make();let data,name,page;h.ctx.MapstoneUI.download=(d,n)=>{data=d;name=n;};h.ctx.MapstoneUI.open=(_app,p)=>page=p;h.app.exportJson();assert.deepEqual(C.parseFile(data),C.validate(h.app.dataDocument()));assert.match(name,/^mapstone_\d{8}\.mapstone$/);h.app.openFile();assert.equal(page,'file');const menu=html.split('<summary>{{ L.exp }}')[1].split('</details>')[0];assert.ok(menu.indexOf('exportJson')<menu.indexOf('exportPng'));assert.doesNotMatch(menu,/openText/);assert.equal(h.app.L().kFlag,'메모');assert.equal(h.app.L().add,'항목 추가');assert.equal(h.app.L().jsonBak,'맵스톤 파일');});
test('Editable PPT includes every item type on one slide within slide bounds',async()=>{const h=make(),calls=[];let slides=0,filename,layout;h.ctx.window.PptxGenJS=class{set layout(value){layout=value;}addSlide(){slides++;return {addText:(v,o)=>calls.push(['text',v,o]),addShape:(v,o)=>calls.push(['shape',v,o]),addImage:o=>calls.push(['image',null,o])};}writeFile(o){filename=o.fileName;return Promise.resolve();}};h.app.state.cfg.showElementDates=true;h.app.state.items.push({id:'post',kind:'sticky',s:-2,e:-2,w:600,h:400,y:1000,color:'#fff5d9',label:'포스트잇 테스트'},{id:'picture',kind:'image',s:40,e:40,w:500,h:400,y:1400,src:'data:image/png;base64,AA=='});const f=h.app.state.items.find(i=>i.kind==='flag'),t=h.app.state.items.find(i=>i.kind==='chev');h.app.connectFlag(f.id,t.id);await h.app.exportPptx();assert.equal(slides,1);assert.equal(layout,'LAYOUT_WIDE');assert.match(filename,/mapstone_\d{8}\.pptx/);assert.equal(calls.filter(c=>c[0]==='image').length,1);for(const item of h.app.state.items.filter(i=>i.kind!=='image'))assert.ok(calls.some(c=>c[0]==='text'&&String(c[1]).includes(item.label)),item.label);for(const [, ,o] of calls){for(const k of ['x','y','w','h'])assert.ok(Number.isFinite(o[k]),k+' '+JSON.stringify(o));assert.ok(o.x>=.349&&o.y>=.349);assert.ok(o.x+o.w<=12.985&&o.y+o.h<=7.151);}assert.ok(calls.some(c=>c[0]==='text'&&String(c[1]).includes(' → ')));});
test('Month picker and +/- cross years while preserving real item dates',()=>{const h=make(),it=h.app.state.items[0],date=h.app.isoOf(it.s);h.app.onStartMonth({currentTarget:{value:'2026-12'}});assert.equal(h.app.state.cfg.startM,12);assert.equal(h.app.isoOf(h.app.state.items[0].s),date);h.app.applyCfg('startM',null,1);assert.equal(h.app.renderVals().startMonthValue,'2027-01');assert.equal(h.app.isoOf(h.app.state.items[0].s),date);h.app.applyCfg('startM',null,-1);assert.equal(h.app.renderVals().startMonthValue,'2026-12');const before=h.app.snapshot();for(const value of ['2026-13','', '1899-12'])h.app.onStartMonth({currentTarget:{value}});assert.equal(h.app.snapshot(),before);h.app.undo();assert.equal(h.app.renderVals().startMonthValue,'2027-01');});
test('NOW tags use immediate custom tooltip and removed settings stay absent',()=>{const tags=[...html.matchAll(/<div[^>]+data-now-tag[^>]*>/g)];assert.equal(tags.length,2);for(const tag of tags){assert.match(tag[0],/onMouseEnter="\{\{ onNowHover \}\}"/);assert.match(tag[0],/onFocus="\{\{ onNowHover \}\}"/);assert.doesNotMatch(tag[0],/title=/);}const h=make();let shown=0;h.ctx.MapstoneUI.showTip=()=>shown++;h.app.onNowHover({});assert.equal(shown,1);const settings=html.split('<sc-if value="{{ showSet }}"')[1].split('<sc-if value="{{ showVer }}"')[0];assert.doesNotMatch(settings,/toggleMagnet|data-cfg="now"|nowToday|L.nowPos/);assert.match(settings,/type="month"/);assert.match(html,/onClick="\{\{ toggleMagnet \}\}"/);});
test('Raw template entry points redirect to the runnable bundle without losing share links',()=>{const guard=html.match(/<script data-entry-guard="">([\s\S]*?)<\/script>/)[1];for(const path of ['src/timeline.dc.html','share-timeline.dc.html','share/schedule-maker.html','개발 일정 및 진행 현황.dc.html','index.html'])for(const base of ['file:///Users/test/mapstone/','https://example.test/mapstone/']){const url=new URL(path+'?share=abc#focus',base),document={documentElement:{style:{}}};let redirected=null;vm.runInNewContext(guard,{URL,document,location:{pathname:url.pathname,href:url.href,search:url.search,hash:url.hash,replace:value=>redirected=value}});assert.equal(redirected,path==='index.html'?null:base+'index.html?share=abc#focus');assert.equal(document.documentElement.style.visibility,path==='index.html'?undefined:'hidden');}assert.ok(html.indexOf('data-entry-guard')<html.indexOf('src="./mapstone-core.js"'));});
test('Common properties start with one-line resizable text and compact date steps',()=>{for(const field of ['label','memo']){const tag=html.match(new RegExp('<textarea[^>]+data-field="'+field+'"[^>]*>'))[0];assert.match(tag,/rows="1"/);assert.match(tag,/height:38px/);assert.match(tag,/resize:vertical/);}const steps=[...html.matchAll(/<div class="ms-date-step ms-stepper"[^>]*>/g)];assert.equal(steps.length,2);for(const step of steps)assert.match(step[0],/height:32px/);assert.equal((html.match(/type="date" value="\{\{ sel[SE]ISO \}\}"[^>]*height:32px/g)||[]).length,2);assert.doesNotMatch(html,/data-field="kind"|data-field="row"|기간 삭제 \(표시 숨김\)/);assert.match(html,/data-field="rowFrom"/);assert.match(html,/data-field="rowTo"/);});
test('Detaching an alert preserves its label position and moves the dot beside it',()=>{const h=make(),target=h.app.state.items.find(i=>i.kind==='chev'),flag=h.app.state.items.find(i=>i.kind==='flag');h.app.connectFlag(flag.id,target.id);h.app.mutate(d=>{const f=d.items.find(i=>i.id===flag.id);f.labelDx=80;f.labelDy=-30;});const view=()=>h.app.renderVals().rowsView.flatMap(r=>r.flags).find(f=>f.id===flag.id),before=view(),history=h.app.state.hist.length;h.app.connectFlag(flag.id,'');const after=view();assert.equal(parseFloat(after.left)+parseFloat(after.labelLeft),parseFloat(before.left)+parseFloat(before.labelLeft));assert.equal(parseFloat(after.top)+parseFloat(after.labelTop),parseFloat(before.top)+parseFloat(before.labelTop));assert.equal(parseFloat(after.dotLeft),parseFloat(after.labelLeft)-23);assert.equal(parseFloat(after.dotTop),parseFloat(after.labelTop)+1);assert.equal(after.connected,false);assert.equal(h.app.state.hist.length,history+1);h.app.undo();assert.equal(view().dotLeft,'-11px');assert.equal(view().connected,true);h.app.connectFlag(flag.id,'');h.app.connectFlag(flag.id,target.id,.5);assert.equal(view().connected,true);assert.equal(view().dotLeft,'-11px');});
test('Alert connection previews live, commits once and undoes as one drag',()=>{const h=make(),targets=h.app.state.items.filter(i=>i.kind==='chev'),flag=h.app.state.items.find(i=>i.kind==='flag');h.app.connectFlag(flag.id,targets[0].id);const history=h.app.state.hist.length;h.app.drag={id:flag.id,mode:'link',x0:0,y0:0,snap:h.app.snapshot(),moved:false};const node={classList:{add(){},remove(){}}};h.app.linkHit=()=>({id:targets[1].id,offset:.25,el:node});h.app.onMove({clientX:20,clientY:30});assert.equal(h.app.state.items.find(i=>i.id===flag.id).targetId,targets[1].id);assert.equal(h.app.state.linkDrag,null);assert.equal(h.app.state.hist.length,history);h.app.stopDrag({clientX:20,clientY:30});assert.equal(h.app.state.hist.length,history+1);h.app.undo();assert.equal(h.app.state.items.find(i=>i.id===flag.id).targetId,targets[0].id);});
test('Detached alerts retain their anchor and opaque labels keep connectors at their edge',()=>{const h=make(),target=h.app.state.items.find(i=>i.kind==='chev'),flag=h.app.state.items.find(i=>i.kind==='flag');h.app.connectFlag(flag.id,target.id);h.app.mutate(d=>{const f=d.items.find(i=>i.id===flag.id);f.labelDx=-300;f.labelDy=0;});let v=h.app.renderVals().rowsView.flatMap(r=>r.flags).find(f=>f.id===flag.id);assert.equal(v.badgeBg,'#fff');assert.ok(v.zIndex>72);assert.ok(parseFloat(v.connPath.split(' H ')[1])<0);h.app.connectFlag(flag.id,'');v=h.app.renderVals().rowsView.flatMap(r=>r.flags).find(f=>f.id===flag.id);assert.equal(v.connected,false);assert.equal(h.app.state.items.find(i=>i.id===flag.id).linkOffset,undefined);assert.doesNotMatch(html,/<sc-if value="\{\{ f.connected \}\}"><span data-link-dot/);});
test('Tooltip toggle persists and announces both modes, and sharing follows export',()=>{const h=make(),messages=[];h.ctx.MapstoneUI.toast=(_app,message)=>messages.push(message);assert.equal(h.app.renderVals().showTooltip,true);h.app.toggleTooltip();assert.equal(h.app.state.cfg.showTooltip,false);h.app.toggleTooltip();assert.equal(h.app.state.cfg.showTooltip,true);assert.match(messages[0],/꺼짐/);assert.match(messages[1],/켜짐/);assert.equal(h.app.L().elementDates,'일자');assert.ok(html.indexOf('onClick="{{ openWorkspace }}"')>html.indexOf('<summary>{{ L.exp }}'));assert.match(fs.readFileSync('mapstone-ui.js','utf8'),/app.state.cfg.showTooltip===false/);});
function make(){let timers=new Map(),id=0,writes=0;const memory=new Map();const document={createElement:()=>({getContext:()=>({font:'',measureText:t=>({width:t.length*7})})}),addEventListener(){},removeEventListener(){}};const ctx={MapstoneCore:C,MapstoneUI:{attach(){return ()=>{}},hideTip(){}},DCLogic:class{props={};setState(p){const patch=typeof p==='function'?p(this.state):p;this.state={...this.state,...patch};this.componentDidUpdate?.();}},window:{localStorage:{getItem:k=>memory.get(k)||null,setItem:(k,v)=>{writes++;memory.set(k,v);}},addEventListener(){},removeEventListener(){},confirm:()=>true},document,console,Date,Math,JSON,setTimeout:fn=>{timers.set(++id,fn);return id;},clearTimeout:id=>timers.delete(id),requestAnimationFrame:fn=>fn(),cancelAnimationFrame(){}};vm.createContext(ctx);vm.runInContext(logic+'\nglobalThis.app=new Component()',ctx);return {app:ctx.app,ctx,memory,timers,writes:()=>writes,flush:()=>{const all=[...timers.values()];timers.clear();all.forEach(fn=>fn());}};}
test('Auto-save stops after real content saved; selection does not resave',()=>{const h=make();h.app.componentDidUpdate();h.flush();assert.equal(h.writes(),1);assert.equal(h.timers.size,0);h.app.setState({sel:h.app.state.items[0].id});h.flush();assert.equal(h.writes(),1);h.app.onTitle({currentTarget:{value:'changed'}});h.flush();assert.equal(h.writes(),2);});
test('Save failure shows warning and does not recurse',()=>{const h=make();h.ctx.window.localStorage.setItem=()=>{throw Error('QuotaExceeded');};h.app.componentDidUpdate();h.flush();assert.match(h.app.state.saved,/실패/);assert.equal(h.timers.size,0);});
test('Eighth-month snap is exact; fifth month returns quarter grid',()=>{const h=make();h.app.state.items=[];h.app.state.cfg.months=2;assert.equal(h.app.snapM(.127,'',null),.125);h.app.state.cfg.months=5;assert.equal(h.app.snapM(.127,'',null),.25);h.app.state.cfg.magnet=false;assert.equal(h.app.snapM(.1234,'',null),.1234);});
test('Two-month configuration and wider zoom accepted',()=>{const h=make();h.app.applyCfg('months',2,0);assert.equal(h.app.state.cfg.months,2);h.app.onWeekPx({currentTarget:{value:String(h.app.zoomToSlider(200))}});assert.ok(Math.abs(h.app.state.cfg.weekPx-200)<1,'200px/week round trip, got '+h.app.state.cfg.weekPx);h.app.onWeekPx({currentTarget:{value:'0'}});assert.equal(h.app.state.cfg.weekPx,h.app.ZMIN);h.app.onWeekPx({currentTarget:{value:'1000'}});assert.equal(h.app.state.cfg.weekPx,h.app.ZMAX);});
test('Zoom slider spreads the usable range instead of crowding the low end',()=>{const h=make();const t=h.app.zoomToSlider(19);assert.ok(t>200&&t<400,'default 19px/week should land mid-track, got '+t);const half=h.app.zoomFromSlider(500);assert.ok(half>40&&half<60,'mid-track should be a moderate zoom, got '+half);});
test('Start and end accept dates and round-trip through month offsets',()=>{const h=make();h.app.state.cfg.months=2;h.app.state.items=[h.app.state.items[0]];const id=h.app.state.items[0].id;h.app.state.sel=id;const it=()=>h.app.state.items.find(i=>i.id===id);h.app.onDateField({currentTarget:{dataset:{field:'s'},value:'2026-02-01'}});assert.equal(it().s,1);assert.equal(h.app.isoOf(1),'2026-02-01');h.app.onDateField({currentTarget:{dataset:{field:'e'},value:'2026-03-01'}});assert.equal(it().e,2);assert.equal(h.app.monthOfISO('2026-01-01'),0);assert.equal(h.app.monthOfISO('not-a-date'),null);assert.equal(h.app.monthOfISO('2026-02-30'),null);});
test('Mouse control toggles without any notice popup',()=>{const h=make();h.app.toggleInteract();assert.equal(h.app.state.interact,true);assert.equal(h.app.state.mouseTipOpen,false);h.app.toggleInteract();assert.equal(h.app.state.interact,false);assert.equal(h.app.state.mouseTipOpen,false);});
test('Renamed controls and new groups are translated in both locales',()=>{const h=make();assert.equal(h.app.DICT.ko.add,'항목 추가');assert.equal(h.app.DICT.ko.interact,'마우스 조작');assert.equal(h.app.DICT.ko.fileG,'불러오기');assert.equal(h.app.DICT.ko.tabSet,'설정');assert.equal(h.app.DICT.ko.panelF,'설정창 보기');assert.match(h.app.DICT.ko.dateHint,/눈금 맞춤/);for(const lang of ['ko','ja'])for(const key of ['editTools','screenG','fileG','moreG','fit','full','interact','tabSet','panelF','dateHint','dateSet','mouseTipMsg','dontShow','importG','shareBtn','jsonBak','helpT','helpTip'])assert.ok(h.app.DICT[lang][key],lang+'.'+key+' missing');});
test('Legacy hidden-duration data remains readable after removing its settings control',()=>{const h=make();h.app.state.sel=h.app.state.items[0].id;h.app.state.items[0].hideDuration=true;const block=h.app.renderVals().rowsView.flatMap(r=>r.chevs).find(i=>i.id===h.app.state.sel);assert.equal(block.dur,'');assert.doesNotThrow(()=>C.validate(h.app.dataDocument()));assert.doesNotMatch(html,/onHideDuration|selHideDuration|기간 삭제 \(표시 숨김\)/);});
test('Alert label moves independently while its link and anchor remain intact',()=>{const h=make(),target=h.app.state.items.find(i=>i.kind==='chev'),flag=h.app.state.items.find(i=>i.kind==='flag');h.app.connectFlag(flag.id,target.id,.5);const before=h.app.renderVals().rowsView.flatMap(r=>r.flags).find(f=>f.id===flag.id);h.app.drag={id:flag.id,kind:'flag',mode:'move',x0:0,y0:0,labelDx:0,labelDy:0,moved:false};h.app.onMove({clientX:60,clientY:30});const after=h.app.renderVals().rowsView.flatMap(r=>r.flags).find(f=>f.id===flag.id);assert.equal(after.left,before.left);assert.equal(after.top,before.top);assert.equal(parseFloat(after.labelLeft)-parseFloat(before.labelLeft),60);assert.equal(parseFloat(after.labelTop)-parseFloat(before.labelTop),30);assert.notEqual(after.connPath,before.connPath);assert.equal(after.targetId,target.id);assert.equal(after.connected,true);assert.doesNotThrow(()=>C.validate(h.app.dataDocument()));});
test('Deleting a selected alert dot detaches the connection without deleting the alert',()=>{for(const key of ['Delete','Backspace']){const h=make(),target=h.app.state.items.find(i=>i.kind==='chev'),flag=h.app.state.items.find(i=>i.kind==='flag');h.app.connectFlag(flag.id,target.id);h.app.state.sel=flag.id;h.app.state.selLinkDot=flag.id;h.app.onKey({key,target:{tagName:'SPAN'},preventDefault(){}});assert.equal(h.app.state.items.find(i=>i.id===flag.id).targetId,'');h.app.undo();assert.equal(h.app.state.items.find(i=>i.id===flag.id).targetId,target.id);}});
test('Element dates toggle preserves timing and exposes start/end labels',()=>{const h=make(),before=JSON.stringify(h.app.state.items),v=h.app.renderVals();assert.equal(v.showElementDates,false);assert.match(v.rowsView[0].chevs[0].dateLabel,/\d{2}\.\d{2}\.\d{2} → \d{2}\.\d{2}\.\d{2}/);h.app.toggleElementDates();assert.equal(h.app.renderVals().showElementDates,true);h.app.toggleElementDates();assert.equal(h.app.renderVals().showElementDates,false);assert.equal(JSON.stringify(h.app.state.items),before);});
test('Alert links persist, follow target changes, undo, detach and reject invalid offsets',()=>{const h=make(),target=h.app.state.items.find(i=>i.kind==='chev'),flag=h.app.state.items.find(i=>i.kind==='flag');h.app.connectFlag(flag.id,target.id,.5);let f=()=>h.app.state.items.find(i=>i.id===flag.id);assert.equal(f().targetId,target.id);assert.equal(f().s,(target.s+target.e)/2);assert.equal(C.validate(h.app.dataDocument()).items.find(i=>i.id===flag.id).targetId,target.id);h.app.mutate(d=>{const t=d.items.find(i=>i.id===target.id);t.s+=1;t.e+=2;t.row='care';});assert.equal(f().row,'care');assert.equal(f().s,(target.s+target.e+3)/2);h.app.undo();assert.equal(f().row,target.row);h.app.mutate(d=>{d.items=d.items.filter(i=>i.id!==target.id);});assert.equal(f().targetId,'');const invalid=h.app.dataDocument();invalid.items.find(i=>i.id===flag.id).linkOffset=2;assert.throws(()=>C.validate(invalid));});
test('Dot drop connects only to range elements and preserves position within target',()=>{const h=make(),target=h.app.state.items.find(i=>i.kind==='chev'),flag=h.app.state.items.find(i=>i.kind==='flag'),node={dataset:{id:target.id},getBoundingClientRect:()=>({left:100,width:200,top:20,height:100}),classList:{remove(){}}};h.ctx.document.elementsFromPoint=()=>[{closest:()=>node}];h.app.drag={mode:'link',id:flag.id};h.app.stopDrag({clientX:150,clientY:50});const linked=h.app.state.items.find(i=>i.id===flag.id);assert.equal(linked.targetId,target.id);assert.equal(linked.linkOffset,.25);assert.equal(linked.linkY,.3);assert.equal(h.app.drag,null);assert.equal(h.app.state.linkDrag,null);h.ctx.document.elementsFromPoint=()=>[];assert.equal(h.app.linkHit({clientX:0,clientY:0}),null);});
test('MM toggles all range durations without changing item timing or individual visibility',()=>{const h=make(),before=JSON.stringify(h.app.state.items);h.app.toggleMM();assert.equal(h.app.renderVals().showMM,false);for(const row of h.app.renderVals().rowsView)for(const block of [...row.chevs,...row.plains])assert.equal(block.dur,'');assert.equal(JSON.stringify(h.app.state.items),before);h.app.toggleMM();assert.equal(h.app.renderVals().showMM,true);assert.ok(h.app.renderVals().rowsView.flatMap(r=>r.chevs).some(b=>b.dur));});
test('AI generated row backgrounds use the settings palette',()=>{const d=C.fromAnalysis({rangeStart:'2026-01-01',rangeEnd:'2026-03-01',rows:[{id:'a',name:'Blue',color:'#0000ff'},{id:'b',name:'None',color:''},{id:'c',name:'Mint',color:'#e7f4f1'}],items:[]});assert.ok(C.rowColors.some(c=>c[1]===d.rows[0].color));assert.equal(d.rows[1].color,undefined);assert.equal(d.rows[2].color,'#e7f4f1');});
test('Short schedules expose dates, 8 divisions and exact 0.125M label',()=>{const h=make();h.app.state.cfg.months=2;h.app.state.cfg.showWeek=true;h.app.state.cfg.weekPx=100;const v=h.app.renderVals();assert.equal(v.subdivisions.length,14);assert.equal(v.timeStep,.125);h.app.state.cfg.durUnit='MM';assert.equal(h.app.durOf(0,.125),'0.125M');assert.match(h.app.dateOf(.125),/2026\.01\.04/);});
test('Week defaults off and toggles labels without changing time grids',()=>{const h=make();assert.equal(h.app.durationWD(0,1),'4 w 3 d');assert.equal(h.app.renderVals().subdivisions.length,0);const before=h.app.renderVals().gridCols.length;h.app.toggleWeek();assert.ok(h.app.renderVals().subdivisions.some(q=>q.label==='1w'));assert.equal(h.app.renderVals().gridCols.length,before);h.app.state.cfg.months=2;h.app.state.cfg.weekPx=100;assert.equal(h.app.renderVals().subdivisions.length,14);});
test('Double click opens properties for the clicked element and focuses its settings',()=>{const h=make(),it=h.app.state.items[0];h.app.state.panel=false;h.app.state.tab='set';let focused=false;h.app.root={querySelector:()=>({focus(){focused=true;},scrollIntoView(){}}),querySelectorAll:()=>[]};h.app.onItemDbl({stopPropagation(){},currentTarget:{dataset:{id:it.id}}});assert.equal(h.app.state.panel,true);assert.equal(h.app.state.tab,'prop');assert.equal(h.app.state.sel,it.id);assert.equal(h.app.state.editing,null);assert.equal(focused,true);});
test('Imported documents reject unknown kinds without replacing current state',()=>{const h=make(),before=h.app.snapshot();assert.throws(()=>h.app.importDocument({rows:[],items:[]}));assert.equal(h.app.snapshot(),before);});
test('All entry point application logic is generated identically',()=>{for(const name of ['share-timeline.dc.html','share/schedule-maker.html'])assert.equal(fs.readFileSync(name,'utf8'),html);});
test('Modal stacking and focus mode CSS protect content visibility',()=>{assert.ok(!/z-index:60;display:flex;align-items:center;justify-content:center;padding:24px/.test(html));assert.match(html,/data-focus="true".*data-toolbar/);assert.match(html,/data-resize/);});
test('Removed kind and row settings cannot change selected elements',()=>{const h=make(),it=h.app.state.items[0];h.app.state.sel=it.id;const before=h.app.snapshot();for(const field of ['kind','row','hideDuration'])h.app.onField({currentTarget:{dataset:{field},value:'flag',type:'select-one'}});assert.equal(h.app.snapshot(),before);assert.doesNotMatch(html,/data-field="(?:kind|row)"/);});
test('Deleting a band endpoint row also removes the band',()=>{const h=make(),band=h.app.state.items.find(i=>i.kind==='band');h.app.state.rowDelId=band.rowTo;h.app.confirmRowDelete();assert.ok(!h.app.state.items.some(i=>i.rowFrom===band.rowTo||i.rowTo===band.rowTo));assert.doesNotThrow(()=>C.validate(h.app.dataDocument()));});
test('Invalid local data is not overwritten before recovery',()=>{const h=make(),bad='{"rows":[],"items":[]}';h.memory.set(h.app.KEY,bad);h.app.componentDidMount();h.flush();assert.equal(h.memory.get(h.app.KEY),bad);assert.match(h.app.state.saved,/JSON 백업/);});
test('Share columns exist in the checked-in schema',()=>{const schema=fs.readFileSync('supabase/schema.sql','utf8');assert.match(schema,/guest_password_hash text/);assert.match(schema,/guest_permission text/);});
test('Text editing creates one undo step per focus session',()=>{const h=make(),it=h.app.state.items[0],before=it.label,focus={currentTarget:{select(){}}};h.app.state.sel=it.id;h.app.beginTextEdit(focus);h.app.onLabelInput({currentTarget:{dataset:{id:it.id},value:'첫 변경'}});h.app.onLabelInput({currentTarget:{dataset:{id:it.id},value:'최종 변경'}});assert.equal(h.app.state.hist.length,1);h.app.undo();assert.equal(h.app.state.items.find(i=>i.id===it.id).label,before);});
test('View-only mode blocks document mutations immediately',()=>{const h=make(),before=h.app.snapshot();h.app.state.readOnly=true;h.app.onTitle({currentTarget:{value:'바뀌면 안 됨'}});h.app.addAt('chev');assert.equal(h.app.snapshot(),before);assert.match(h.app.state.saved,/보기 전용/);});
test('Timeline items expose keyboard selection and editing',()=>{const h=make(),it=h.app.state.items[0],event=key=>{const currentTarget={dataset:{id:it.id}};return {key,target:currentTarget,currentTarget,preventDefault(){this.prevented=true;}};};h.app.onItemKey(event(' '));assert.equal(h.app.state.sel,it.id);h.app.onItemKey(event('Enter'));assert.equal(h.app.state.editing,it.id);assert.match(html,/role="button" tabindex="0" aria-label="\{\{ b\.label \}\}" onKeyDown="\{\{ onItemKey \}\}"/);});
test('Explicit share links win over stored room sessions',()=>{const ui=fs.readFileSync('mapstone-ui.js','utf8');assert.match(ui,/if\(shareId\)setTimeout\(\(\)=>open\(app,'workspace'\),100\);else if\(code\)/);assert.match(ui,/readOnly:this\.readOnly/);});
test('Codex revisions and durable anonymous rate limit are checked in',()=>{const api=fs.readFileSync('supabase/functions/mapstone-api/index.ts','utf8'),schema=fs.readFileSync('supabase/schema.sql','utf8'),migration=fs.readFileSync('supabase/migrations/20261003160230_harden_share_and_rate_limit.sql','utf8'),built=fs.readFileSync('index.html','utf8').slice(0,500);assert.match(html,/APP_VER = 'v9\.47'/);assert.match(html,/v: 'v9\.35', agent: 'Codex', title: '행간 높이 조절 경계 개선'/);assert.match(built,/<title>MapStone · 일정 Maker<\/title>/);for(const sql of [schema,migration]){assert.match(sql,/guest_password_hash text/);assert.match(sql,/mapstone_take_rate_limit/);}assert.match(api,/await allowAnonymous\(req\)/);assert.doesNotMatch(api,/new Map<string,number\[\]>/);});
test('Toolbar is one row without the NOW shortcut',()=>{assert.equal((html.match(/class="ms-toolbar-row"/g)||[]).length,1);assert.match(html,/L\.viewG/);assert.match(html,/L\.screenG/);assert.match(html,/class="ms-tool-menu"/);assert.equal((html.match(/onClick="\{\{ nowToday \}\}"/g)||[]).length,0);});
test('Toolbar menus close outside, controls follow the annotated order, and week counts stay hidden',()=>{const h=make(),open=new Set(),a={removeAttribute(){open.delete(a);}},b={removeAttribute(){open.delete(b);}};open.add(a);open.add(b);h.app.root={querySelectorAll:()=>[...open]};h.app.closeToolMenus({target:{closest:()=>b}});assert.deepEqual([...open],[b]);h.app.closeToolMenus({target:{closest:()=>null}});assert.equal(open.size,0);assert.ok(html.indexOf('toggleMagnet')<html.indexOf('togglePanel'));assert.ok(html.indexOf('openClear }}')<html.indexOf('togglePanel'));assert.ok(html.indexOf('toggleMagnet')<html.indexOf('openImport }}'));assert.doesNotMatch(html,/\{\{ c\.weeks \}\}/);assert.equal((html.match(/\{\{ L\.magnetF \}\} \{\{ magnetState \}\}/g)||[]).length,0);});
test('Issue connectors stay continuous over work and reference ranges',()=>{const h=make(),base={row:'gs',span:1,variant:'solid',memo:'',color:'#e22a21'};h.app.state.items=[{...base,id:'work',kind:'chev',lane:0,s:0,e:2,label:'작업'},{...base,id:'reference',kind:'plain',lane:1,s:0,e:2,label:'참고 구간'},{...base,id:'work-issue',kind:'flag',lane:0,s:1,e:1,label:'작업 이슈'},{...base,id:'reference-issue',kind:'flag',lane:1,s:1,e:1,label:'참고 이슈'}];const layout=h.app.rowLayout().gs;assert.equal(layout.modes['work-issue'].mode,'strip');assert.equal(layout.modes['reference-issue'].mode,'strip');const flags=h.app.renderVals().rowsView.find(r=>r.id==='gs').flags;for(const f of flags){assert.ok(['work','reference'].includes(f.targetId));assert.equal(f.top,f.targetId==='work'?'27px':'71px');assert.equal(parseFloat(f.connH),parseFloat(f.stripTop)-11);}assert.match(html,/stroke="\{\{ f\.color \}\}" stroke-width="1\.5"/);});

test('Height drag snaps to lanes with magnet and always catches at row boundaries',()=>{const h=make();const it=h.app.state.items.find(i=>h.app.boxKind(i.kind));const g={id:it.id,mode:'bottom',...h.app.heightBounds(it)};const r0=g.rows[0],laneH=h.app.laneH();h.app.state.cfg.magnet=true;assert.equal(h.app.snapEdge(r0.top+laneH-6+5,'bottom',g.rows),r0.top+laneH-6);assert.equal(h.app.snapEdge(r0.top+6+3,'top',g.rows),r0.top+6);h.app.state.cfg.magnet=false;assert.equal(h.app.snapEdge(r0.bottom-6+5,'bottom',g.rows),r0.bottom-6);assert.equal(h.app.snapEdge(r0.top+laneH+3,'bottom',g.rows),r0.top+laneH+3);});
test('Row divider double-click fits items or restores default height; NOW outside range asks first',()=>{const h=make();const row=h.app.state.rows[0];h.app.mutate(d=>{d.rows[0].h=900;});h.app.onRowFit({stopPropagation(){},currentTarget:{dataset:{row:row.id}}});const fitted=h.app.state.rows[0].h;assert.ok(fitted<900&&fitted>=h.app.laneH()+14);const empty={id:'empty',name:'빈 행',h:500};h.app.mutate(d=>{d.rows.push(empty);});h.app.onRowFit({stopPropagation(){},currentTarget:{dataset:{row:'empty'}}});assert.equal(h.app.state.rows.find(r=>r.id==='empty').h,undefined);
  h.app.mutate(d=>{d.cfg.startY=2000;d.cfg.startM=1;d.cfg.months=2;});h.app.nowToday();assert.equal(h.app.state.nowOutOpen,true);const before=h.app.state.items[0];const date=h.app.isoOf(before.s);h.app.nowExtend();assert.equal(h.app.state.nowOutOpen,false);assert.equal(h.app.isoOf(h.app.state.items[0].s),date);assert.ok(h.app.state.now<=h.app.state.cfg.months);});

test('MD unit converts 1MM to 22MD and the toolbar button follows the setting',()=>{const h=make();assert.equal(h.app.state.cfg.durUnit,'MD');h.app.onDurUnit({currentTarget:{dataset:{unit:'MM'}}});assert.equal(h.app.durOf(0,1.5),'1.5M');h.app.onDurUnit({currentTarget:{dataset:{unit:'MD'}}});assert.equal(h.app.durOf(0,1.5),'33MD');const v=h.app.renderVals();assert.equal(v.durUnit,'MD');assert.match(v.mmToolTip,/MD/);assert.match(html,/data-tip="\{\{ mmToolTip \}\}"/);assert.match(html,/onDoubleClick="\{\{ fitWidth \}\}" type="range"/);});
test('Week labels never overlap and animation can be switched off without delaying deletes',()=>{const h=make();h.app.state.cfg.showWeek=true;h.app.state.cfg.weekMode='actual';for(const wp of [5,40,100]){h.app.state.cfg.weekPx=wp;const q=h.app.renderVals().subdivisions.map(x=>[parseFloat(x.left),x.label.length*5.5]);for(let i=1;i<q.length;i++)assert.ok(q[i-1][0]+q[i-1][1]+3<=q[i][0],'overlap at weekPx '+wp);}
  h.app.onAnim({currentTarget:{dataset:{anim:'off'}}});assert.equal(h.app.state.animate,false);assert.equal(h.app.renderVals().animAttr,'off');const id=h.app.state.items[0].id;h.app.state.sel=id;h.app.deleteSel();assert.ok(!h.app.state.items.some(i=>i.id===id));});

test('Week labels drop from the tail of each month and mark the cut with an ellipsis',()=>{const h=make();h.app.state.cfg.showWeek=true;h.app.state.cfg.weekMode='actual';h.app.state.cfg.weekPx=11;const labels=h.app.renderVals().subdivisions.map(q=>q.label);assert.ok(labels.some(l=>l.endsWith('…')),'expected a truncated label');assert.ok(labels.includes('1w')||labels.includes('1w…'));for(const l of labels.filter(l=>l.endsWith('…')))assert.match(l,/^\d+w…$/);h.app.state.cfg.weekPx=200;assert.ok(!h.app.renderVals().subdivisions.some(q=>q.label.endsWith('…')));h.app.toggleDurUnit();assert.equal(h.app.state.cfg.durUnit,'MM');h.app.toggleDurUnit();assert.equal(h.app.state.cfg.durUnit,'MD');});

test('Toolbar matches the one-row layout: extras under 더보기, share under 내보내기, accented analysis, rich help',()=>{const more=html.split('<summary>{{ L.moreG }}')[1].split('</details>')[0];for(const k of ['addPlain','addBand','addSticky'])assert.match(more,new RegExp(k));const exp=html.split('<summary>{{ L.exp }}')[1].split('</details>')[0];assert.match(exp,/openWorkspace/);assert.match(html,/ms-accent" onClick="\{\{ openImport \}\}"/);assert.match(html,/role="switch" aria-checked="\{\{ interactChecked \}\}"/);const ui=fs.readFileSync('mapstone-ui.js','utf8');assert.match(ui,/page==='help'\?'사용법'/);const help=fs.readFileSync('mapstone-help.js','utf8');for(const k of ['toolbar','analyze','edit','now','rows','props','settings'])assert.match(help,new RegExp(k+":'data:image/jpeg;base64,"));});

test('Clear all leaves one untitled row, bands start inside their row, and bands move/stretch across rows',()=>{const h=make();h.app.doClearAll();assert.equal(h.app.state.items.length,0);assert.equal(h.app.state.rows.length,1);assert.equal(h.app.state.rows[0].name,'');assert.equal(h.app.state.title,'일정 제목을 입력해주세요');
  const h2=make();const rows=h2.app.state.rows;h2.app.state.focusRow=rows[1].id;h2.app.addBand();const band=h2.app.state.items.find(i=>i.id===h2.app.state.sel);assert.equal(band.rowFrom,rows[1].id);assert.equal(band.rowTo,rows[1].id);
  assert.match(html,/data-mode="btop"/);assert.match(html,/data-mode="bbot"/);const v=h2.app.renderVals();assert.equal(v.showElementDates,false);assert.equal(v.durUnit,'MD');assert.equal(v.showTooltip,true);assert.match(html,/class="ms-focus-exit"/);});

test('Toolbar folds in order instead of wrapping, icon buttons carry tooltips, and tooltip duration is a setting',()=>{assert.match(html,/\.ms-toolbar-row \{ display:flex;flex-wrap:nowrap/);for(const c of ['c1','c2','c3','c4'])assert.match(html,new RegExp('\\.ms-toolbar-row\\.'+c));assert.match(html,/class="ms-tool-menu ms-view-more"/);assert.match(html,/ms-lbl-short">\{\{ L\.importShort \}\}/);assert.match(html,/data-tip="\{\{ L\.clearAll \}\}"/);assert.match(html,/data-tip="\{\{ L\.rowAdd \}\}"/);const h=make();assert.equal(h.app.DICT.ko.category,'세션');assert.equal(h.app.state.tipHold,false);h.app.toggleTipHold();assert.equal(h.app.state.tipHold,true);assert.equal(h.memory.get('mapstone.tipHold'),'1');const ui=fs.readFileSync('mapstone-ui.js','utf8');assert.match(ui,/e\.isComposing/);assert.match(ui,/setTimeout\(\(\)=>\{if\(tip===mine\)hideTip\(\);\},3000\)/);});

test('New sessions, overlap rule row and inline title inputs follow v9.42 wording and sizing',()=>{const h=make();assert.equal(h.app.DICT.ko.newRow,'신규 세션');assert.equal(h.app.DICT.ko.overlapF,'항목들이 겹쳐지는 경우');assert.equal(h.app.DICT.ko.opShrink,'다른 항목 줄이기');assert.match(h.app.DICT.ko.interactTip,/^1\. 마우스 휠 : 확대\/축소\n2\. 오른버튼 드래그 : 화면 이동\(패닝\)$/);h.app.state.cfg.overlap='moveSelf';const v=h.app.renderVals();assert.equal(v.overlapName,'선택된 항목이 위치변경');assert.match(v.overlapDesc,/아래 줄/);assert.doesNotMatch(html,/width:180px;border:1px solid #000/);assert.match(fs.readFileSync('mapstone-ui.js','utf8'),/lh\*5\+frame/);});

test('Single-key shortcuts use physical keys, buttons advertise them, and the raw template never paints',()=>{const ui=fs.readFileSync('mapstone-ui.js','utf8');for(const c of ['KeyF','KeyD','KeyM','KeyT','KeyW','KeyS','Comma'])assert.match(ui,new RegExp(c+':'));assert.match(ui,/e\.shiftKey\?\{KeyF:\(\)=>fitWidth\(app\)\}/);for(const t of ['· D','· T','· W','· Shift+F','· F','· S / ,'])assert.ok(html.includes(t),t);assert.match(html,/<style>x-dc\{display:none!important\}/);const base=fs.readFileSync('scripts/bundle-base.html','utf8');assert.doesNotMatch(base,/fill="#5b3fd1"/);assert.match(base,/ms-boot-bar/);});

test('Save-as, credit, centered session header, alternating months and faint week lines',()=>{const ui=fs.readFileSync('mapstone-ui.js','utf8');assert.match(ui,/showSaveFilePicker\(\{suggestedName:name/);assert.match(ui,/ms-help-credit/);assert.match(html,/data-credit=""[^>]*>MapStone \{\{ appVer \}\}<br>\{\{ L\.credit \}\}/);assert.match(html,/justify-content:center;text-align:center;padding:8px 12px;[^"]*">\{\{ L\.category \}\}/);const h=make();const v=h.app.renderVals();assert.equal(v.cols[0].bg,'transparent');assert.equal(v.cols[1].bg,'rgba(255,255,255,.06)');const lines=()=>h.app.renderVals().gridCols.filter(g=>/-wl/.test(g.key)).length;h.app.state.cfg.weekPx=19*2;assert.equal(lines(),0);h.app.state.cfg.weekPx=19*4;assert.ok(lines()>0);});

test('Zoom keeps the view centre, scroll does not re-render per frame, day lines dot above 600%, tooltips carry weekdays',()=>{const h=make();h.app.state.cfg.weekPx=19*7;const dots=h.app.renderVals().gridCols.filter(g=>/-dl/.test(g.key));assert.ok(dots.length>0);assert.match(dots[0].color,/repeating-linear-gradient/);h.app.state.cfg.weekPx=19*5;assert.equal(h.app.renderVals().gridCols.filter(g=>/-dl/.test(g.key)).length,0);
  const board={scrollLeft:1000,clientWidth:800,getBoundingClientRect:()=>({left:0})};h.app._board=board;h.app.state.cfg.weekPx=40;h.app.zoomTo(80);assert.equal(h.app.state.cfg.weekPx,80);h.app.componentDidUpdate();assert.equal(board.scrollLeft,192+(1000+400-192)*2-400);
  assert.doesNotMatch(html,/this\.setState\(\{ sx: el\.scrollLeft/);assert.match(html,/data-ind-thumb=""/);const ui=fs.readFileSync('mapstone-ui.js','utf8');assert.match(ui,/iso\+'\('\+w\+'\)'/);assert.doesNotMatch(ui,/ms-tip-title'\}\)\)/);assert.equal(h.app.DICT.ko.weekdays,'일월화수목금토');assert.match(html,/aria-label="\{\{ k\.label \}\}"[^>]*onMouseEnter="\{\{ onHover \}\}"/);});

test('App badge shows the MapStone name and icon, and favicon/loader share the same mark',()=>{assert.doesNotMatch(html,/>Prototype \{\{ appVer \}\}</);assert.match(html,/<\/svg>MapStone \{\{ appVer \}\}<\/button>/);const fav=html.match(/<link rel="icon" href="([^"]+)"/)[1];assert.match(decodeURIComponent(fav),/M296 320l28 28-28 28-28-28z/);const base=fs.readFileSync('scripts/bundle-base.html','utf8');assert.ok(base.includes(fav));assert.match(base,/<\/svg>MapStone<\/div>/);assert.match(html,/<title>MapStone · 일정 Maker<\/title>/);});

test('Release notes carry agent tags without Codex title prefixes',()=>{const h=make();const rel=h.app.RELEASES;assert.ok(rel.every(r=>['Codex','Claude Code','Claude Design'].includes(r.agent)));assert.ok(!rel.some(r=>/^Codex/.test(r.title||'')));assert.equal(rel.find(r=>r.v==='v9.15').title,undefined);assert.equal(rel.find(r=>r.v==='v9.20').agent,'Codex');assert.equal(rel.find(r=>r.v==='v9.10').agent,'Claude Code');assert.equal(rel.find(r=>r.v==='v1.0').agent,'Claude Design');const v=h.app.renderVals();assert.ok(v.releases[0].agentBg);assert.match(html,/\[\{\{ r\.agent \}\}\]/);assert.match(html,/vector-effect="non-scaling-stroke"/);});
