const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),C=require('../mapstone-core.js'),crypto=require('node:crypto').webcrypto;
function fixture(fetch){const store=new Map(),ctx={MapstoneCore:C,window:{confirm:()=>true},document:{},crypto,AbortSignal,localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)},fetch};vm.runInNewContext(fs.readFileSync('mapstone-ui.js','utf8'),ctx);const document=C.fromAnalysis({title:'메인 제목',rangeStart:'2026-10-01',rows:[{id:'r',name:'QA'}],items:[]});let id=0;const app={state:{...document,vNote:'변경 메모',hist:[],future:[]},sync:{endpoint:'https://example.test'},uid:()=> 'test-'+(++id),setState(p){Object.assign(this.state,typeof p==='function'?p(this.state):p);},snapshot(){const {title,cfg,rows,items,notes,now}=this.state;return JSON.stringify({title,cfg,rows,items,notes,now});},applySnap(s){Object.assign(this.state,JSON.parse(s));}};return {ui:ctx.window.MapstoneUI,app,ctx};}
test('Cloud save retains input on unknown outcome and retries the same immutable version id',async()=>{const calls=[];let fail=true;const {ui,app}=fixture(async(url,opt)=>{if(opt.method==='GET')return {ok:true,status:200,json:async()=>[{id:calls.at(-1).body.id,sequence:1,created_at:'2026-10-06T12:00:00Z',note:calls.at(-1).body.note,document:calls.at(-1).body.document}]};const body=JSON.parse(opt.body);calls.push({url,body});if(fail){fail=false;throw Error('network');}return {ok:true,status:201,json:async()=>({id:body.id,sequence:1,created_at:'2026-10-06T12:00:00Z',note:body.note,document:body.document})};});await ui.saveCloudVersion(app);assert.equal(app.state.versions.length,0);assert.equal(app.state.vNote,'변경 메모');assert.equal(app.state.versionBusy,false);await ui.saveCloudVersion(app);assert.equal(app.state.versions.length,1);assert.equal(calls[0].url,calls[1].url);assert.equal(calls[0].body.id,calls[1].body.id);assert.equal(calls[1].body.document.title,'메인 제목');assert.equal(calls[1].body.document.versions.length,0);assert.equal(calls[1].body.author,undefined);assert.equal(app.state.versions[0].date,'2026-10-06');assert.equal(app.state.vNote,'');});
test('Cloud restore preserves management history and provides one undo snapshot',async()=>{let saved;const {ui,app}=fixture(async()=>({ok:true,status:200,json:async()=>saved}));app.state.versions=[{id:'old',projectId:'project',snap:''}];const before=app.snapshot();saved={sequence:4,document:{...JSON.parse(before),title:'복원 제목'}};await ui.restoreCloudVersion(app,app.state.versions[0]);assert.equal(app.state.title,'복원 제목');assert.equal(app.state.hist.at(-1),before);assert.equal(app.state.versions.length,1);assert.equal(app.state.versionBusy,false);});
test('Version schema isolates owners and makes retries unique within a project',()=>{const sql=fs.readFileSync('supabase/migrations/20261006143000_version_library.sql','utf8'),api=fs.readFileSync('supabase/functions/mapstone-api/index.ts','utf8');assert.match(sql,/owner_id uuid references auth.users/);assert.match(sql,/primary key\(project_id,id\)/);assert.match(sql,/for update/);assert.match(sql,/owner is distinct from p_owner/);assert.match(sql,/enable row level security/);assert.match(api,/ids.length!==2\|\|new Set\(ids\).size!==2/);assert.match(api,/GEMINI_API_KEY/);});
test('Gemini report removes Markdown decorations while retaining item and date changes',()=>{
  const api=fs.readFileSync('supabase/functions/mapstone-api/index.ts','utf8');
  const expression=api.match(/const plain=(report\.replace\([\s\S]*?\.trim\(\));return json\(\{report:plain/)[1];
  const report='### 핵심 변화\n**테스트 작업** 종료일: `2026-10-10` → **2026-10-17**\n---\n* __추가 검수__: 동일 기간에 겹침';
  const plain=vm.runInNewContext(expression,{report});
  assert.equal(plain.includes('**'),false);assert.equal(plain.includes('#'),false);assert.equal(plain.includes('`'),false);
  assert.match(plain,/테스트 작업 종료일: 2026-10-10 → 2026-10-17/);assert.match(plain,/추가 검수: 동일 기간에 겹침/);
});
test('Deleting a version preserves document, other projects, cancellations and failed requests',async()=>{
 let requests=0,fail=false;const {ui,app,ctx}=fixture(async(url,opt)=>{requests++;assert.equal(opt.method,'DELETE');assert.match(url,/\/project-a\/versions\/same$/);if(fail)throw Error('network');return {ok:true,status:200,json:async()=>({deleted:true})};});
 const v={id:'same',sequence:2,projectId:'project-a'};app.state.versions=[v,{id:'same',projectId:'project-b'},{id:'other',projectId:'project-a'}];const snap=app.snapshot();
 ctx.window.confirm=()=>false;assert.equal(await ui.deleteSavedVersion(app,v),false);assert.equal(requests,0);assert.equal(app.state.versions.length,3);
 ctx.window.confirm=()=>true;app.state.readOnly=true;assert.equal(await ui.deleteSavedVersion(app,v),false);assert.equal(requests,0);app.state.readOnly=false;
 fail=true;assert.equal(await ui.deleteSavedVersion(app,v),false);assert.equal(app.state.versions.length,3);assert.equal(app.state.versionBusy,false);
 fail=false;assert.equal(await ui.deleteSavedVersion(app,v),true);assert.equal(app.state.versions.length,2);assert.equal(app.state.versions[0].projectId,'project-b');assert.equal(app.snapshot(),snap);assert.equal(app.state.versionBusy,false);
});
test('Separate projects keep independent cloud histories through file round trips and title changes',async()=>{
  const db=new Map();const {ui,app}=fixture(async(url,opt)=>{const project=url.split('/version-projects/')[1]?.split('/')[0];let value;if(url.endsWith('/version-projects'))value=[...db].map(([id,vs])=>({id,title:vs.at(-1).document.title}));else if(opt.method==='POST'){const b=JSON.parse(opt.body),vs=db.get(project)||[];value=vs.find(v=>v.id===b.id);if(!value){value={...b,sequence:vs.length+1,created_at:'2026-10-07T00:00:00Z'};vs.push(value);}db.set(project,vs);}else value=[...(db.get(project)||[])].reverse();return {ok:true,status:200,json:async()=>value};});
  app.state.title='프로젝트 A';await ui.saveCloudVersion(app);const idA=app.state.versionProjectId,exported=C.parseFile(C.serializeFile({...JSON.parse(app.snapshot()),versionProjectId:idA,versions:app.state.versions}));
  Object.assign(app.state,C.fromAnalysis({title:'프로젝트 B',rangeStart:'2026-10-01',rows:[{id:'b',name:'B'}],items:[]}));await ui.saveCloudVersion(app);const idB=app.state.versionProjectId;assert.notEqual(idA,idB);assert.equal(app.state.versions.length,1);assert.equal(app.state.versions[0].sequence,1);
  Object.assign(app.state,exported,{title:'프로젝트 A 제목 수정'});await ui.saveCloudVersion(app);assert.equal(app.state.versionProjectId,idA);assert.equal(db.get(idA).length,2);assert.equal(db.get(idB).length,1);assert.ok(app.state.versions.every(v=>v.projectId===idA));
  app.state.versionProjectId=null;app.state.title='프로젝트 B';await ui.refreshVersionHistory(app);assert.equal(app.state.versionProjectId,idB);assert.equal(app.state.versions.length,1);
});
test('An in-flight save cannot attach its old history to a newly imported project',async()=>{
  let release,saved;const gate=new Promise(r=>release=r);const {ui,app}=fixture(async(url,opt)=>{if(opt.method==='POST'){const b=JSON.parse(opt.body);saved={...b,sequence:1,created_at:'2026-10-07T00:00:00Z'};await gate;return {ok:true,status:201,json:async()=>saved};}return {ok:true,status:200,json:async()=>[saved]};});const pending=ui.saveCloudVersion(app);Object.assign(app.state,C.fromAnalysis({title:'새 프로젝트',rangeStart:'2026-10-01',rows:[{id:'new',name:'새 행'}],items:[]}),{vNote:'새 작업 메모'});release();await pending;assert.equal(app.state.title,'새 프로젝트');assert.equal(app.state.versionProjectId,null);assert.equal(app.state.versions.length,0);assert.equal(app.state.vNote,'새 작업 메모');assert.equal(app.state.versionBusy,false);assert.throws(()=>C.validate({...JSON.parse(app.snapshot()),versionProjectId:0}));
});
