const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),C=require('../mapstone-core.js'),crypto=require('node:crypto').webcrypto;
function fixture(fetch){const store=new Map(),ctx={MapstoneCore:C,window:{},document:{},crypto,AbortSignal,localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)},fetch};vm.runInNewContext(fs.readFileSync('mapstone-ui.js','utf8'),ctx);const document=C.fromAnalysis({title:'메인 제목',rangeStart:'2026-10-01',rows:[{id:'r',name:'QA'}],items:[]});let id=0;const app={state:{...document,vNote:'변경 메모',hist:[],future:[]},sync:{endpoint:'https://example.test'},uid:()=> 'test-'+(++id),setState(p){Object.assign(this.state,typeof p==='function'?p(this.state):p);},snapshot(){const {title,cfg,rows,items,notes,now}=this.state;return JSON.stringify({title,cfg,rows,items,notes,now});},applySnap(s){Object.assign(this.state,JSON.parse(s));}};return {ui:ctx.window.MapstoneUI,app};}
test('Cloud save retains input on unknown outcome and retries the same immutable version id',async()=>{const calls=[];let fail=true;const {ui,app}=fixture(async(url,opt)=>{const body=JSON.parse(opt.body);calls.push({url,body});if(fail){fail=false;throw Error('network');}return {ok:true,status:201,json:async()=>({id:body.id,sequence:1,created_at:'2026-10-06T12:00:00Z',note:body.note,document:body.document})};});await ui.saveCloudVersion(app);assert.equal(app.state.versions.length,0);assert.equal(app.state.vNote,'변경 메모');assert.equal(app.state.versionBusy,false);await ui.saveCloudVersion(app);assert.equal(app.state.versions.length,1);assert.equal(calls[0].url,calls[1].url);assert.equal(calls[0].body.id,calls[1].body.id);assert.equal(calls[1].body.document.title,'메인 제목');assert.equal(calls[1].body.document.versions.length,0);assert.equal(calls[1].body.author,undefined);assert.equal(app.state.versions[0].date,'2026-10-06');assert.equal(app.state.vNote,'');});
test('Cloud restore preserves management history and provides one undo snapshot',async()=>{let saved;const {ui,app}=fixture(async()=>({ok:true,status:200,json:async()=>saved}));app.state.versions=[{id:'old',projectId:'project',snap:''}];const before=app.snapshot();saved={sequence:4,document:{...JSON.parse(before),title:'복원 제목'}};await ui.restoreCloudVersion(app,app.state.versions[0]);assert.equal(app.state.title,'복원 제목');assert.equal(app.state.hist.at(-1),before);assert.equal(app.state.versions.length,1);assert.equal(app.state.versionBusy,false);});
test('Version schema isolates owners and makes retries unique within a project',()=>{const sql=fs.readFileSync('supabase/migrations/20261006143000_version_library.sql','utf8'),api=fs.readFileSync('supabase/functions/mapstone-api/index.ts','utf8');assert.match(sql,/owner_id uuid references auth.users/);assert.match(sql,/primary key\(project_id,id\)/);assert.match(sql,/for update/);assert.match(sql,/owner is distinct from p_owner/);assert.match(sql,/enable row level security/);assert.match(api,/ids.length!==2\|\|new Set\(ids\).size!==2/);assert.match(api,/GEMINI_API_KEY/);});
test('Gemini report removes Markdown decorations while retaining item and date changes',()=>{
  const api=fs.readFileSync('supabase/functions/mapstone-api/index.ts','utf8');
  const expression=api.match(/const plain=(report\.replace\([\s\S]*?\.trim\(\));return json\(\{report:plain/)[1];
  const report='### 핵심 변화\n**테스트 작업** 종료일: `2026-10-10` → **2026-10-17**\n---\n* __추가 검수__: 동일 기간에 겹침';
  const plain=vm.runInNewContext(expression,{report});
  assert.equal(plain.includes('**'),false);assert.equal(plain.includes('#'),false);assert.equal(plain.includes('`'),false);
  assert.match(plain,/테스트 작업 종료일: 2026-10-10 → 2026-10-17/);assert.match(plain,/추가 검수: 동일 기간에 겹침/);
});
